server:
  port: 10080
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 10240000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.240.20:3306/SXXF?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: CleanApp12#$.
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1 from dual
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  mvc:
    date-time: yyyy-MM-dd HH:mm
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/view/
  redis:
    host: 121.196.185.252
    port: 10001
    password: CleanApp12#$.
    database: 1

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.easy.scaffold.sys.sysUserMenu.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
pagehelper:
  support-methods-arguments: true
  page-size-zero: auto
  auto-dialect: mysql
  params: count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero

logging:
  config:
    classpath: log4j.properties

#是否需要输入验证码
captcha:
  enable: true